### ISSUE TITLE
nonstop music

### ISSUE THREAD

**Issue by Tienuz** [netmix/radio-station#344] opened 2021-04-29 08:22 UTC
Is there a possibilty to add nonstop music as a show, without adding it as a show?

We play 24/7 music but when there is no DJ we play non stop music. As a result that now it looks like there is nothing on air, when there is no DJ.

**Comment by kairandles** [comment] 2021-04-29 08:24
Hey, I've got something simmilar open on #331 so feel free to check out for now though we just schedule a non stop 'show' with the stations logo as the presenter image and call it Non Stop Hits etc

**Comment by Tienuz** [comment] 2021-04-29 09:20
Thanks, it is the same issue.

 

Martijn.

 

Van: Kai Randles ***@***.***> 
Verzonden: donderdag 29 april 2021 10:25
Aan: netmix/radio-station ***@***.***>
CC: Tienuz ***@***.***>; Author ***@***.***>
Onderwerp: Re: [netmix/radio-station] nonstop music (#344)

 

Hey, I've got something simmilar open on #331 <https://github.com/netmix/radio-station/issues/331>  so feel free to check out for now though we just schedule a non stop 'show' with the stations logo as the presenter image and call it Non Stop Hits etc

**Comment by tonyzeoli** [comment] 2021-04-29 14:11
@Tienuz , 
Duplicate of #331 

Bcause @kairandles has this issue already, I'm going to close this and refer to # #331.

**Closed by tonyzeoli** 2021-04-29 14:11 UTC
