### ISSUE TITLE
[Shows] Display a list/grid of all hosts/djs on a page

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#172] opened 2020-04-02 21:56 UTC
**Is your feature request related to a problem? Please describe.**

Many stations have a list of all Host/DJs on the station website.

**Describe the solution you'd like**

Add page template for all station Host/DJs in alpha order by last name.
Add About Host / DJ text. Add Show(s) featuring Host DJ and link to Show(s).
Show number of posts attributed to Host / DJ and add link to posts by Host / DJ.
Display social media icons for host DJ. Pull from Profile.
Display contact Host / DJ by email icon. Pull from Profile.

In admin settings, add ability to show/hide all email addresses for all host/djs on this page.

**Describe alternatives you've considered**

Someone could create a custom post type, but then you'd be adding Host DJs in duplicate and you couldn't manage both pages well.

**Additional context**

Host DJs could also get listed in the Directory. Just all names with links to their host/dj pages on their connected site.

**Comment by tonyzeoli** [comment] 2020-04-02 21:59
@majick777 This should also be created automatically if we add "Reporters/Journalists" as a user role.

**Comment by majick777** [comment] 2020-04-14 02:01
Possible duplicate of #1

**Comment by majick777** [comment] 2020-04-14 02:49
I am closing this here as I have copied the issue notes to #1

**Closed by majick777** 2020-04-14 02:49 UTC
Labels: duplicate, feature
