### ISSUE TITLE
Patreon change of domain and logo

### ISSUE THREAD

**Issue by PKABKMY** [netmix/radio-station#203] opened 2020-05-01 06:58 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PKABKMY** [comment] 2020-05-01 06:59
It would be good if there was an option to change the domain and logo in the Patreon system. There is a local service in my country and I have no way to change it here.

**Comment by majick777** [comment] 2020-05-01 15:57
This feature was intended specifically for Patreon use, not for any image/URL. 
Currently you can filter the output array for the Show page using the filter: `radio_station_show_page_blocks`
I've added a filter `radio_station_show_patreon_button` for the next version which will be released shortly, so you can use that also to change it to something else manually if you want.

**Closed by majick777** 2020-05-01 15:57 UTC
