### ISSUE TITLE
[Conflict Check] Show Shift detects conflicts with itself

### ISSUE THREAD

**Issue by MattMski** [netmix/radio-station#281] opened 2020-11-15 19:22 UTC
I have an issue with a show where that specific day/time shows that it's conflicting with itself. Maybe this is coming from a previous deleted permanently show with the same time, I'm not sure but not sure how to fix this. Let me know if you want more information.

 
![issue](https://user-images.githubusercontent.com/6692764/99194549-90c52d00-2745-11eb-91e6-430ef3f44442.PNG)

**Comment by tonyzeoli** [comment] 2020-11-16 03:02
@MattMski you are stating that you had the exact same show with the exact same show time, but you deleted it. Now, you have a new show with the exact same name and time and it's conflicting with that previously deleted show, or so it seems. Is that correct? This is the first time this issue's come up, so we'll take a look and see if that's the cause. If you can maybe provide a step-by-step analysis of what you created, deleted, and recreated, that would be helpful.

Assigned to @majick777 for a look.

**Comment by majick777** [comment] 2020-11-16 07:22
@MattMski Not too long ago we added the extra check with the last shift in the Schedule in case that overlaps with a newly added shift into the next week... It seems this is what is being tripped up as a conflict here, whereas the shift should not check against itself in this case (and this is probably because it is the last shift in the week?) 

Though I was unable to reproduce the issue when saving the last shift in a schedule myself, I have added an extra logic check to the development version for this part anyway so that the Shift does not check against itself here. You can try it out and see if it resolves the issue and report back. (If the conflict message still reappears, it should now also come with a brief conflict debug message.)

I've added these changes to the development version for now so you can test them out:
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing

**Comment by MattMski** [comment] 2020-11-16 20:46
> @MattMski you are stating that you had the exact same show with the exact same show time, but you deleted it. Now, you have a new show with the exact same name and time and it's conflicting with that previously deleted show, or so it seems. Is that correct? This is the first time this issue's come up, so we'll take a look and see if that's the cause. If you can maybe provide a step-by-step analysis of what you created, deleted, and recreated, that would be helpful.
> 
> Assigned to @majick777 for a look.

That is correct. I can't really say much cause I did permanently delete the show first round but there is no other show in existence with the same time nor was there anything in the database.

**Comment by majick777** [comment] 2020-11-16 23:44
@MattMski If the conflict has disappeared already without the code in the development version, and I couldn't reproduce it myself, we can probably safely assume it's a glitch that's only going to come up at a particular day/time in the week, combined with when the Shift being saved is also the last shift of the week. 

Given this makes it really hard to reproduce, and we now already have a patch in place in came it comes up again anyway (that will continue to be included), I'm going to close this here as resolved. If similar happens again just post another screenshot and re-open, and we can take another look. Thanks for the report!

**Closed by majick777** 2020-11-16 23:44 UTC
Labels: bug
