### ISSUE TITLE
[Schedule Table] Show Entry on calendar does not appear to display full duration

### ISSUE THREAD

**Issue by marcel-za** [netmix/radio-station#338] opened 2021-04-22 13:17 UTC
All shows look like they are only 30min long in the calendar

Created a number of Shows & included their start & end times.

On the Master Schedule Table View , it looks like each Show is only 30min long, regardless of the actual duration.

![CleanShot 2021-04-22 at 15 12 05](https://user-images.githubusercontent.com/28527561/115721009-e6010c80-a37d-11eb-8ff5-58a30c08909d.png)

**Comment by tonyzeoli** [comment] 2021-04-23 10:19
@majick777 please investigate, thanks.

**Comment by tonyzeoli** [comment] 2021-04-23 10:20
@marcel-za Did this happen with an update to the plugin? Can you take the development version from here on Git and see if that fixes the issue?

**Comment by majick777** [comment] 2021-04-24 00:27
@marcel-za Because it is a dark-based background, the normally faint highlight lines look more like solid borders. I can see there has been a style added via Elementor to change these solid lines to dashed:

`.elementor-602 .elementor-element.elementor-element-d99929a #master-program-schedule td div {
    border-top: 1px dashed #EEEEEE;
}`

If you just use `border-top: none;` they disappear and the issue is resolved, Similarly If you want to just use something darker to match the dark background but still have the lines, use something like `border-top: 1px solid #555555;`

**Comment by tonyzeoli** [comment] 2021-11-08 14:59
@majick777 has supplied a CSS style fix for this ticket, so we'll consider this closed. Please reopen a new ticket if any further issues.

**Closed by tonyzeoli** 2021-11-08 14:59 UTC
Labels: support request
