### ISSUE TITLE
[Current Show Widget/Shortcode] Does Not Display Current Shows ending at midnight

### ISSUE THREAD

**Issue by Ajames0807** [netmix/radio-station#253] opened 2020-07-27 23:06 UTC
Hello

I have just updated to v2.3.3.1 and the current show widget and short code is no longer displaying the current show. I was wondering if this is a bug and if others are experiencing this?

**Comment by cbeattie89** [comment] 2020-07-27 23:30
Having the same issue. All shows are active and scheduled correctly, and are properly highlighted in the master schedule - but nothing on the current show widget and short-code.

**Comment by tonyzeoli** [comment] 2020-07-27 23:40
@Ajames0807  and @cbeattie89 Thanks for reporting this. I've confirmed on our demo site that the widget is not displaying the current show.

@majick777 I've assigned this. Can you take a look, please? Thanks. We'll have to get out a fix for this asap.

**Comment by larryl79** [comment] 2020-07-27 23:57
I've experiencing same with widget and schedule override.

**Comment by cbeattie89** [comment] 2020-07-28 00:10
Just a heads up - it looks like my widget's started working again. Not sure if this was something you did on the developer's end, or just a strange quirk of timing.

**Comment by larryl79** [comment] 2020-07-28 00:26
> Just a heads up - it looks like my widget's started working again. Not sure if this was something you did on the developer's end, or just a strange quirk of timing.

I've just checked on mine and same started, upcoming widget started working again as well.

**Comment by Ajames0807** [comment] 2020-07-28 08:17
Yes mine also seems to be working OK now 👍

**Comment by astevens93** [comment] 2020-07-28 10:43
Hello just wanted to confirm that this is the same issue that I referred to in this comment?

https://github.com/netmix/radio-station/issues/241#issuecomment-664641002

**Comment by tonyzeoli** [comment] 2020-07-28 15:54
@astevens93 Let's then wait on this ticket until 10 pm to 12 am EST and see if that's the issue or it was just something that needed to clear the cache after expiry. If the issue resolves itself, I'll close this ticket when confirmed.

**Comment by astevens93** [comment] 2020-07-28 21:03
Hi @tonyzeoli 

10pm GMT (London) has arrived for me, and I'm getting No Show scheduled on my site and the demo site.  See attached screenshots with the time recorded. From experience it will be like this until 12am and then it will go back to showing this.

A while back there was a problem with the 10pm show not highlighting as 'On Air' in the tabbed schedule, I wonder if the two are related?

My site:
![image](https://user-images.githubusercontent.com/67294458/88721093-ce159880-d11d-11ea-8570-16e09d6fd6bb.png)

The demo site: http://radiostationdemo.com/widgets/
![image](https://user-images.githubusercontent.com/67294458/88721143-e1c0ff00-d11d-11ea-96e2-d3b15badafef.png)

**Comment by Ajames0807** [comment] 2020-07-28 21:10
Hello, yes I am getting the same now, it disappeared as soon as it went 10pm
Our site: www.wearemaidstone.com

**Comment by astevens93** [comment] 2020-07-28 23:13
In fact post midnight it doesn’t seem to be resolving. Not yet at least. But it definitely breaks at 10pm.

**Comment by tonyzeoli** [comment] 2020-07-29 02:04
@astevens93 @Ajames0807 @larryl79 @cbeattie89 okay, I’ve confirmed on the demos site they 10 pm is blank for radiostationdemo.com.

We’ll try to get a fix for this ASAP.

Please stay tuned and will let you know what comes of it in the next 24 hours. @majick777 is currently planning a move of living space so please be patient while we work out when he can address and we can issue a hot fix.

**Comment by majick777** [comment] 2020-07-29 04:27
@astevens93 @Ajames0807 @larryl79 @cbeattie89
There was an error for Current Shows ending at midnight, arises from fixes appied in #241 for 2.3.0

I have updated the latest development release version of the plugin (2.3.3.2) to include this fix:
https://github.com/netmix/radio-station/releases

Please confirm the issue is fixed and we can push this version to the WordPress SVN also.

**Comment by astevens93** [comment] 2020-07-29 08:10
Thanks @majick777 ...  I have loaded Version 2.3.3.2 and will check back at 10pm GMT time for myself to confirm.
Hope the move goes well.

**Comment by tonyzeoli** [comment] 2020-07-29 14:04
Hey everyone - here's what I'm going to do. Let's let everyone on the thread here download the development version today then check the 10 pm to 12 pm shows on their schedules. If the fix is working for all testers, then I'll roll out the official update tomorrow morning between 9 am and 12 noon EST.

**Comment by astevens93** [comment] 2020-07-29 21:13
To confirm in Develop Version 2.3.3.2 it is now 10.12pm GMT (London) and the on air show scheduled up until midnight displays correctly in the widget. Thank you.

**Comment by tonyzeoli** [comment] 2020-07-30 00:32
@astevens93 thanks for reporting back...i'm waiting for the demo site at 10 pm EST. Once I've confirmed that fixed the issue, I'll release the official version late tonight or tomorrow EST.

**Comment by Ajames0807** [comment] 2020-07-30 23:08
Thank you for releasing the fix so quickly. It was working fine on our website up until 12am British time, but is now not displaying again. I've checked on @astevens93 website and it appears they are also experiencing the same issue.

**Comment by astevens93** [comment] 2020-07-30 23:19
Thanks for flagging this @Ajames0807. You are right, I am experiencing this. I won't be staying up til 2am (when this current show shift finishes) to check, but I can presume now that when the show starting at midnight finishes it will go back to normal.

**Comment by tonyzeoli** [comment] 2020-07-30 23:27
@astevens93 @Ajames0807 Okay, thanks for reporting. @majick777 will have to take another look. I'll keep my eye on this eastern time tonight at 10 pm and see what happens for radiostationdemo.com. It's impractical to release three hot fixes in a week, so I hope we can narrow this done if it's still an issue.

**Comment by tonyzeoli** [comment] 2020-07-31 02:49
It's 10:48 pm EST and RadioStationDemo.com Upcoming Shows widgets are displaying the content. So, I'm thinking this is now an after 12-midnight issue. I'll look out for that in an hour's time and see where we are at.

**Comment by tonyzeoli** [comment] 2020-07-31 04:07
<img width="1552" alt="Screen Shot 2020-07-31 at 12 05 25 AM" src="https://user-images.githubusercontent.com/4053819/88999136-a8c18f80-d2c1-11ea-8578-a93d77b7b33b.png">

I confirm it's 12:05 am est and widgets are displaying content.

**Comment by astevens93** [comment] 2020-07-31 06:06
Thanks @tonyzeoli I’m just thinking about this and I wonder if yours showed correctly because at that time the show on air for you would have been Show 9’ which runs 11pm - 1am.

@Ajames0807 and myself both had a show where the shift began at midnight 12am, and we experienced the issue.

I can see from the radio station demo site, Show 1 begins Sunday 12.00am. So I would be interested to know if for that show, which begins at midnight, you experience the same.

That’s the only reason I could think you are not experiencing the issue we and @Ajames0807 are...

Just a thought and I guess will need to be tested.

![B6B22145-858A-449E-9432-20813A842356](https://user-images.githubusercontent.com/67294458/89005256-e511e180-d2fb-11ea-9b0c-5987752047ce.jpeg)

**Comment by astevens93** [comment] 2020-07-31 09:59
Hmmm. I've done a bit of testing today and I can't replicate what we experienced @Ajames0807 

1. I tried doing a Schedule Override for the day 12am - 1pm (that worked fine and showed as 'now on air' as it should)
2. I also cleared all the scheduled shows for the day and made a long scheduled show (not an override an actual show) running 12am - 4pm).  This also showed fine as it should

Slightly frustrating i can't replicate it again.  I will check back at midnight tonight to see if it resolves itself.

**Comment by tonyzeoli** [comment] 2020-07-31 13:41
@astevens93 Thanks for working on this to narrow down the issue. I will try to reschedule a show for tonight to start at 12 midnight and see if that knocks out the view. Will let you know what I find out.

**Comment by Ajames0807** [comment] 2020-07-31 13:42
@astevens93 it's very odd!

@tonyzeoli 

I've been playing around with the timezones to see if I can recreate the issue. I changed to NZST (GMT + 12) - Auckland, which would be about 01:31am and I'm not displaying my scheduled show. 

I again changed the timezone to +14 (GMT + 14) - Kiritimati and I'm again not showing a scheduled show. Their time would be about 3.31am. 

I then tried AKDT (GMT - 11) Anchorage, which is about 05.31am and it was then displaying our show that starts at 5am.

So it's definitely something to do with maybe the show starting at 12am - as our station have evening/early morning shows that start at 12am and go through to 5am, we have nothing displaying on the current show on air. 

Thanks you for your help!

**Comment by tonyzeoli** [comment] 2020-07-31 14:42
@astevens93 I have set a show to start at 12 midnight EST tonight (Friday) and tomorrow night (Saturday). Let's see what happens.

**Comment by astevens93** [comment] 2020-07-31 23:31
Yes be interesting to see what happens with you @tonyzeoli .  Despite not being able to replicate the issue through manual intervention today, I am still experiencing it with the scheduled show starting at midnight...   the problem still remains for me.

**Comment by Ajames0807** [comment] 2020-07-31 23:33
Hi, yep still experiencing the issue here also. For your info, the show that is on our schedule now started 10pm yesterday and finishes at 1pm. As soon as it hit 12am, it display no show.

**Comment by tonyzeoli** [comment] 2020-08-02 04:04
Okay, so I'm looking at RadioStationDemo.com right now and it's 12:03 AM. Up until 12, all shows starting at 12 displayed in the widgets. Starting at 12, all shows starting at 1 am appear in the widgets.

I can't replicate the issue.

**Comment by Ajames0807** [comment] 2020-08-02 23:06
Strange - it was never an issue before v2.3.3.1 and it keeps happening each night, as soon as it turns 12am.  Can I ask, if you could try London timezone when it gets to 12am london time?

**Comment by astevens93** [comment] 2020-08-02 23:15
It's puzzling. I've deleted all of the midnight start shows, binned them, created afresh. Still the same. I've removed the filter for displaying the Day from my functions.php file, still the same.
The only thing @Ajames0807 and I have in common are the timezone I guess.  Bang on 12am it will break.

I've found a few other UK sites running Radio Station and they get the same. I assume they are running Version 2.3.3.2 as well as me and @Ajames0807 ...

**https://shedfm.uk/ (schedule has been checked - they have a show 12am - 6am, yet right now there is No Scheduled Show or even any up-coming show... when there should be.**

![image](https://user-images.githubusercontent.com/67294458/89134544-d99e0080-d51d-11ea-96be-a6e322aad2f9.png)
![image](https://user-images.githubusercontent.com/67294458/89134547-e0c50e80-d51d-11ea-8f82-09ae2fd515a4.png)

**https://electricradio.co.uk/ are the same.**

![image](https://user-images.githubusercontent.com/67294458/89134554-ef132a80-d51d-11ea-8303-d8f2ee0a3cd3.png)
![image](https://user-images.githubusercontent.com/67294458/89134561-f9cdbf80-d51d-11ea-8923-f802b45c9a29.png)

**Comment by tonyzeoli** [comment] 2020-08-03 06:11
@astevens93 and @Ajames0807  I think I misunderstood the issue. I thought it was:

- show starting at 11 pm and stopping at 12 am
- show starting at 12 am and stopping at 1 am

But what I'm now realizing is, it's a show _SPANNING_ 11 pm start to 1 am end having the issue. Is that accurate? The show has to cross over midnight and into the next hour.

I spoke to @majick777 about this tonight and he's going to include some method to test without having to wait for the actual time of the issue to see the issue reveal itself.

I'll also set the RadioStationDemo show schedule for tonight, Monday Aug. 3, to have a show cross over the the midnight hour starting at 11 and stopping at 1 am to see if I can replicate the issue.

**Comment by astevens93** [comment] 2020-08-03 06:28
Thank you for investigating further. I am unsure about the show spanning midnight scenario, as the problem both @Ajames0807 and I are experiencing (and by the looks of it 2 others I found running the plugin)... is we have shows beginning at Midnight, in the GMT time zone, and as soon as midnight hits, the widget breaks. It thinks there is no show scheduled.

I haven’t stayed up to see when it comes back on, but my assumption is it is at the next show scheduled.

My deductions are;
- it happens in GMT timezone (as you did not experience the issue)
- the show begins at midnight (or at least it happens at midnight - your spanning midnight testing might help us find this out)

**Comment by tonyzeoli** [comment] 2020-08-03 06:34
@astevens93 take a look now. I've set a show spanning 11 pm to 4 am right now. Look at the widgets page.

**Comment by astevens93** [comment] 2020-08-03 06:38
@tonyzeoli I am seeing the show on air just fine (it’s 7.37am here in London).  However you are seeing No show scheduled I assume?

![2F3C4555-A915-4838-A4AD-E71A95BF4598](https://user-images.githubusercontent.com/67294458/89153173-4cc66780-d55c-11ea-98c2-cda5cb5c4b64.png)

**Comment by tonyzeoli** [comment] 2020-08-03 06:44
Right, I"m seeing what you're seeing in the screenshot. So, the widget is missing data when it spans the 12 midnight hour, correct?

**Comment by tonyzeoli** [comment] 2020-08-03 06:50
@astevens93 Okay, so I set the shows back to not span the midnight hour and all data displays. So, yes, the spanning the midnight hour is the issue, I believe.

@majick777 I've confirmed this issue with @astevens93 and @Ajames0807. When a show spans the midnight hour, all show scheduling data in the widget disappears. See the widget screenshot that @astevens93 posted just prior to this message and you'll see all show scheduling data and countdown timer missing from the widget.

I've reopened this issue.

**Comment by astevens93** [comment] 2020-08-03 06:56
Thank you!

**Comment by tonyzeoli** [comment] 2020-08-03 06:58
@astevens93 I just spoke to @majick777 now and he's going to have a go at it and figure this out.

No problem. Good think I couldn't sleep tonight and was able to stay up and work through this now. But I could have just set any show to start at 11 and span the midnight hour to whatever time...4am, 6am, 8pm...and the result probably would have been the same.

Thanks for keeping on top of this. Great to have an extra set of eyes to help us see things we might miss.

**Comment by majick777** [comment] 2020-08-03 14:34
@tonyzeoli @astevens93 @Ajames0807 @cbeattie89 @larryl79

Thanks for all your input and testing, since we've managed to go from an intermittant bug to a reproducable one, it looks like I finally have something. The issue was mostly because the current day (today) was being used as the start of the schedule week of dates, so this was not picking up split shift shows starting the previous day for Current and Upcoming Shows, as the date would mismatch. So the answer was to start the schedule week when matching a day earlier. Then I went through and added consistency so each of the widgets does this the same way noe.

To track this down and test, I added a way to override the current time used for the widgets (this works only for widgets.) You can now add `?date=x&month=x&time=xx:xx` to the page where your widgets display, and it will use the provided as the current time (also supports `&year=xxxx` but that is optional.) Also note the countdown is browser javascript and will not be accurate while using this override. 

It was a little tricky to thread through the override to all parts of the code, but fortunately it was already in most places for use in a future feature. So if there are any further issues on this front, this will make things a lot easier for anyone to test the widget/shortcode display without having to wait around for shows to start and end. :-)

Added to 2.3.3.3 development release. If we can get confirmations this resolves the issue, we can push it to WP SVN.

**Comment by astevens93** [comment] 2020-08-03 14:56
Hi @majick777 you've done your magic yet again.  Thank you for bearing with us and getting this fixed.  And to you @tonyzeoli. 

I've tested a few days and times and it seems to work!

![image](https://user-images.githubusercontent.com/67294458/89196087-a2713300-d5a1-11ea-9227-0c9291809777.png)

**Comment by tonyzeoli** [comment] 2020-08-03 15:06
@majick777 There's one minor issue. The 24-hour time setting for the widgets is missing the "am" and "pm."

**Comment by tonyzeoli** [comment] 2020-08-03 15:18
@majick777 Whoops, okay, I was wrong. 24-hour format is supposed to say 11:00 to 12:00 or 13::00 to 14:00. There's no AM / PM. Duh! Sorry! My mistake!

**Comment by tonyzeoli** [comment] 2020-08-03 15:19
This issue is now resolved. Releasing new version shortly.

**Closed by tonyzeoli** 2020-08-03 15:19 UTC
Labels: bug

**Comment by Ajames0807** [comment] 2020-08-03 23:10
To confirm all working now! Thanks so much!
