### ISSUE TITLE
[Conflict Checker] Shift conflict checking does not respect overnight shows

### ISSUE THREAD

**Issue by neosonic2** [netmix/radio-station#232] opened 2020-06-23 23:41 UTC
I am using (and very much enjoying) the Radio Station plugin with a local LPFM community radio station that has a very busy show schedule made up of volunteer DJs and hosts. Some of these shows extend into the wee hours of the next morning, and this has resulted in shift conflicts being generated by the plugin when none actually exist. I believe this is because the schedule section on the show editor page does not have support for shows that extend into the next day.

For example, one of our shows runs from Sunday evening at 10 PM to Monday morning at 2 AM, and another show runs from Monday evening at 9 PM to Tuesday morning at 12 AM. The Radio Station plugin currently sees these shows as being in conflict with each other because the plugin probably thinks the Monday show ends at 12 AM on Monday (which would cut into the Sunday show as it extends into 2 AM on Monday) rather than 12 Am on Tuesday as it does in the real world, since the plugin doesn't have a way to select an end day, only a start day.

To reproduce the issue, create two shows and schedule one for Sunday from 10 PM to 2 AM, and schedule the other for Monday from 9 PM to 12 AM.

I am running the latest release of WordPress at time of writing as well as the latest release of the Radio Station plugin.

An example of this busy show schedule can be found at https://www.rochesterfreeradio.com/schedule (this is our old WordPress site using a different radio station plugin but I have transferred the schedule to the new WP site I am developing for the station).

**Comment by tonyzeoli** [comment] 2020-06-24 04:17
@neosonic2 Thanks for reporting this issue. I've assigned it to @majick777 to take a look. Please hold while we work through this issue. Thank you.

**Comment by tonyzeoli** [comment] 2020-06-24 04:29
@majick777 This is also r[eported by another user in the support forum here.](https://wordpress.org/support/topic/styling-questions-4/#post-13027483)

"2) Based on your reply on another post here, I used CSS to hide rows/times for which I dont have shows. But I found an issue. If you scroll down to last show “The Loft with Troi Tyler”, it is scheduled for 9pm to 2pm. But since I have hidden rows for 1am and 2am the description is showing 9:00pm to 1200am as show timing when it should say 900pm to 2am. For some reason hiding a row also changes the data displayed in the description."

**Comment by majick777** [comment] 2020-06-24 09:46
@neosonic2 As it happens I have recently updated some code to do with the Shift Checker in the latest development version, including some changes regarding overnight shifts. Could you install that and see if the issue persists so we can determine if there is further investigation needed here? 
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing

**Comment by neosonic2** [comment] 2020-06-24 13:41
@majick777 I just installed the development release as per your instructions and am now on plugin version 2.3.1.5 as shown in the WordPress admin. However, the schedule conflict warning continues to appear at the top of each admin page and the information in the warning has not changed. Is there anything I need to do to re-check for conflicts or etc.?

**Comment by majick777** [comment] 2020-06-25 05:27
@neosonic2 Thanks I will take a further look then. The conflict check should refresh automatically... I actually suspect this one may be due to the start/end of the week rollover rather than midnight shifts but will investigate.

**Comment by majick777** [comment] 2020-06-27 07:02
@neosonic2 I have done some fixes on this which should hopefully resolve this issue.
Added to development version 2.3.1.6 for 2.3.2 release.
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing

**Comment by neosonic2** [comment] 2020-06-29 22:02
@majick777 Thanks for this update. However, the issue still seems to be persisting on my end, though now it says I am conflicting with a different show than the one the plugin mentioned previously. The plugin says the show scheduled for 10 PM Sunday through 2 AM Monday morning now conflicts with a show scheduled Fridays from 10 PM to Saturday at 2 AM. So....I'm not quite sure what could be going on here LOL.

**Comment by majick777** [comment] 2020-07-01 11:18
@neosonic2 It's just that the shift conflict checking logic is a little tricky to get one's head around. So basically since we changed to date based calculations for the schedule calculations, I made the same changes for the shift checking, but it turned out the shift checking is actually better without the date-based as the logic "leak" with doing it that we is having to recheck whether the first and last shifts overlap anyway.

Try development version 2.3.1.8 I have had another go at getting the logic right to cover all possible cases (as there are 5 different ways a shift can overlap with another shift.)

**Comment by neosonic2** [comment] 2020-07-01 13:11
@majick777 Good morning, and thank you for that explanation, it helps me better understand how the shift conflict checking system works. Unfortunately, though, it seems that upgrading to development version 2.3.1.8 only reverted us back to the former state of things :( in other words, the show on Sunday from 10 PM to Monday at 2 AM no longer conflicts with the Friday show as I mentioned earlier, but now is back to conflicting with the Monday show that airs from 9 PM to midnight. Is there anything you'd like me to check or adjust on my end?

**Comment by majick777** [comment] 2020-07-01 14:06
@neosonic2 Hmmm I am not getting a conflict anymore with either of those time slots. Can you let me know your timezone setting, WordPress start of week setting and whether it is for the same show or not. It's hard to fix something I can no longer reproduce and this information might let me do that.

**Comment by pozitronios** [comment] 2020-07-01 16:52
@majick777  I do have the same issue, i believe you can reproduce this if you schedule shows that go beyond midnight.
i dont know if it helps but here is an export of show sample data that reproduce this
[sampleradio.WordPress.2020-07-01.zip](https://github.com/netmix/radio-station/files/4859233/sampleradio.WordPress.2020-07-01.zip)

**Comment by astevens93** [comment] 2020-07-01 17:30
Sorry to add to your problems, I am not sure if this is related or not. But also on Dev 2.3.1.8 now and I have a scheduled show conflict before which this update fixed.
But now for some reason I am unable to save new show shifts for a show, it always disables it, despite no show conflict. I can't get it to save and enable.

See attached screen grab of error. Despite unchecking 'disabled' and then clicking 'Save shifts' then 'Update' - it reverts back to Disabled.

It is not a show conflict either, as there is no show this date/time.

<img width="947" alt="Screenshot 2020-07-01 at 18 27 41" src="https://user-images.githubusercontent.com/67294458/86273843-bef80500-bbc8-11ea-8dce-1d9fed0e52b1.png">

**Comment by neosonic2** [comment] 2020-07-01 17:41
@majick777 My WordPress timezone setting is EST (America/New_York), start of week setting is Monday, and the two shows that are in conflict with each other are Sunday evening from 10 PM until Monday at 2 AM, and Monday evening at9 PM until Tuesday at midnight (three hours later).

**Comment by majick777** [comment] 2020-07-02 05:31
@neosonic2 Thanks that let me track it down, there was something deeper in the code, a midnight timestamp for the shift sort ordering was being set to the wrong date, which meant the conflict checker was running on a misordered schedule.
@pozitronios Hopefully this sorts your issue to if not report back with what conflicts you are getting.
@astevens93 The improvement in the shift checker logic needed one last tweak in checking against each other, and without that was disabling shifts on saving that actually had no conflicts. That should be sorted now too.

So try out development version 2.3.1.9 with all these changes and let me know if there are any specific issues remaining.

**Comment by astevens93** [comment] 2020-07-02 08:07
Thanks @majick777 - this seems to work for me now. Hope it does for you @neosonic2 and @pozitronios also.

**Comment by pozitronios** [comment] 2020-07-02 13:30
@majick777 so using dev. version 2.3.1.9 will solve this?
In order to be more precise, while a get a notice
![image](https://user-images.githubusercontent.com/66794856/86364598-0e017100-bc81-11ea-828f-0c4d66b9a43e.png)
it doesn't highlight a conflict in shifts and doesn't disable any shifts
![image](https://user-images.githubusercontent.com/66794856/86364761-443ef080-bc81-11ea-9ca6-509e03ba73f2.png)
:)

**Comment by majick777** [comment] 2020-07-02 15:00
@pozitronios Yes the conflict notice should disappear with 2.3.1.9, let us know if it doesn't.

**Comment by neosonic2** [comment] 2020-07-04 04:47
@majick777 The 2.3.1.9 update has resolved my issue - thank you very much for all your hard work on this!! :)

**Comment by majick777** [comment] 2020-07-05 04:56
@neosonic2 Thanks for bearing with us that was sure not an easy one. :-)

**Closed by majick777** 2020-07-05 04:56 UTC
Labels: bug, development
