### ISSUE TITLE
On air now Avatar Pic Quality

### ISSUE THREAD

**Issue by XLRradio** [netmix/radio-station#208] opened 2020-05-05 19:42 UTC
@tonyzeoli @majick777  sorry guys to bombard you today but we are noticing things now, 
why is the On air now widget avatar less quality pic than the show pic where the pic it comes from?
i mean why is the avatar on the on air now widget of less quality? The on air now pic is the same pic as the show pic and the featured image  is there a way to fix this?

**Comment by tonyzeoli** [comment] 2020-05-05 20:17
I would consider this a support request and not a bug or feature issue. In
the future, please delineate your activity to the appropriate forum.

This is probably not a plugin issue as much as it's how WordPress handles
images and what size you select to add the image to the Show Avatar section.

Please check this post:
https://pixelgrade.com/docs/faq/improve-quality-images-wordpress/

I would also post to the WordPress.org Support Forums to ask the question.

We're using the standard method of pulling an image once it's been
uploaded. We don't do anything to the image with the plugin, so it's likely
a WordPress issue that you should get support from WordPress for.

**Comment by XLRradio** [comment] 2020-05-05 20:47
@tonyzeoli thank you for that info i will try the stuff they advise on that website

**Comment by tonyzeoli** [comment] 2020-05-05 21:34
Sure, I'm closing this as it's not a bug or feature request.

**Closed by tonyzeoli** 2020-05-05 21:34 UTC
