### ISSUE TITLE
[Master Schedule] Move Time Zone and left align above Genres

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#133] opened 2020-01-12 02:30 UTC
**Describe the bug**

Having the time zone out to the right in its own column forces genres to a second row when genres has multiple entries. In mobile devices it seems a bit forced. We might as well just simplify and either move it into Show Infor or move it above the Genres line.

**Comment by majick777** [comment] 2020-01-12 02:44
Duplicate of #96 ?

**Comment by majick777** [comment] 2020-01-12 02:57
Okay I split the lines, however have left the right alignment on the timezone for now, do you think that is sufficient?

**Comment by tonyzeoli** [comment] 2020-01-12 03:40
I would move it left :)

When it's in mobile, it looks weird hanging out over there.

**Comment by majick777** [comment] 2020-01-12 10:16
Okie dokes. Done.

**Comment by tonyzeoli** [comment] 2020-01-13 01:38
Move it above and not below Genres, please. Genres will always break to a second line in mobile and I just think it looks better to have Genres the last thing before the calendar. Also, I would say match the font size of Genres, as well.

**Comment by majick777** [comment] 2020-01-16 04:19
This one is done, and I've adjusted the font sizes to be the same now.

**Closed by majick777** 2020-01-16 04:19 UTC
Labels: bug, development
