### ISSUE TITLE
[AJAX Conflict] Version 2.3.2 conflict with AJAX calls using save_post

### ISSUE THREAD

**Issue by pozitronios** [netmix/radio-station#243] opened 2020-07-20 09:40 UTC
**Describe the bug**
Radio Station Version 2.3.2 conflicts with toolset views plugin.

The problem seems to appear when creating/editing/trashing a view, it does not save and is forever loading.

This is just to bring this issue to your attention as I have found a temporary workaround: downgrade to the previous version of radio station while working with toolset, and then upgrading again.

You may close this issue for now, it is FYI

**Comment by tonyzeoli** [comment] 2020-07-20 13:23
Thanks for letting us know. It's always helpful for the community to push issues into our issue tracker for resolution. We appreciate your report!

@majick will take a look and we'll get out a fix for this as soon as possible. We'll probably release it as a development version for you and the minority of users who might experience it and then add it to the next the next release. So, when we fix it, you'll be asked to take the development version for now until 2.3.3 comes around. 

Question - are you using the free version of Toolset or the PRO version?

**Comment by pozitronios** [comment] 2020-07-20 19:21
Pro version, toolset hasn't got a free version

**Comment by tonyzeoli** [comment] 2020-07-21 14:17
Ah, I think they used to have a free version, but no longer. Okay, that's going to be hard to test against because it's a PRO plugin and we just can't go around paying for plugins to test against. I might have a PRO version myself for a client I did work for last year. I'll look and will ask @majick777 what he suggests we do here to test against a premium plugin that we don't have a license key for.

**Comment by pozitronios** [comment] 2020-07-21 15:15
Toolset types used to have a free version but not anymore.  Since it doesn't seem to affect the site's functionality and there is a workaround, I wouldn't consider this critical, just wanted to bring it to your attention and hopefully it is going to get sorted in the future.

**Comment by tonyzeoli** [comment] 2020-07-21 15:23
@pozitronios Got it. I'd say you're right about the level of priority. Most of the sites I've seen use Radio Station aren't really generating custom post types. They usually just use Radio Station with WordPress core functionality and aren't doing much of anything else. Toolset is a popular post type generator plugin - as I said, I've used it in the past. But it's probably not as widely used with broadcaster or webcasters at this point. That's really just guesswork, but I'd say it's the exception rather than the rule. But, it is popular, so I'll ask @majick777 what he thinks and we'll see if it's something that needs to be addressed. With such a popular plugin, it may affect a small percentage of users, but they would - like you - be a little more advanced in doing more with their website than just hosting a site and the schedule. We might want to also report this to them and see what they say about it. As it would be easier fo them to test it and see if it's something they are doing, rather than what we are doing.

**Comment by tonyzeoli** [comment] 2020-07-21 15:31
@pozitronios Toolset doesn't have a good way to submit an issue - I sent them a note through their Business form, because I don't want to create a login for their community forum, which I don't think will get me anywhere. Would you mind logging in with your PRO license and submitting the issue to their team and then reference this post in your note, so they can follow up and test with Radio Station, since we don't have a Toolset license.

**Comment by tonyzeoli** [comment] 2020-07-21 22:44
@majick777 How do you propose we address this issue with Toolset, when we don't have the licensed version of the plugin to test against?

**Comment by BGJamboree** [comment] 2020-07-22 02:00
Seems the same issues are happening with Elementor that pozitronios mentioned for Toolset.  It does have a free version so perhaps a resolution with one would tackle the problem for all.  I was just able to pinpoint the conflict to Radio Station and Elementor not working together and wanted you to be aware.

**Comment by pozitronios** [comment] 2020-07-22 06:53
@tonyzeoli  I have already contacted our guy who can get through to them and astonishingly enough I got a reply saying that there may be a problem with the ajax code found in pos-types-admin.php. I am not a coder so I don't know if that is of any help.
@BGJamboree can you be more specific where and what doesn't work with elementor?

**Comment by BGJamboree** [comment] 2020-07-22 12:02
When trying to post or update the process takes forever only to give a false completion.  No changes are actually submitted when using Elementor.  It would take a minimum of 5 minutes for the page to attempt to publish or update but when checking the front end, there were no changes actually published.

**Comment by pozitronios** [comment] 2020-07-22 12:07
@BGJamboree I can confirm that.

**Comment by tonyzeoli** [comment] 2020-07-22 18:52
@pozitronios @BGJamboree thanks for the reports - I did get through to Toolsets and they sent us a developer login. So, we’re all set now to explore this issue. @majick777 will probably check in shortly on this issue and we’ll get out a fix for it. Thanks for getting them to identify where it might be conflicting with the ajax code.

**Comment by pozitronios** [comment] 2020-07-23 14:44
@tonyzeoli @majick777  It also affects the wordpress customizer: when you press update it gives a false negative warning, however it updates and all changes are saved regardless. From what I have seen so far it affects anything that updates with ajax on the backend.

**Comment by majick777** [comment] 2020-07-23 17:26
@pozitronios Can you indicate which page/interface in Toolset you are experiencing the problem?
@BGJamboree Similarly with Elementor, I am not sure where you are seeing a problem, the plugin post types are not editable by Elementor by default as they just use the Classic Editor, I have installed Elementor but not sure how to reproduce a problem here I have not had a conflict so far.

**Comment by tonyzeoli** [comment] 2020-07-24 03:57
@majick777 @pozitronios said this above: from toolset types, they suggested there may be a problem with the ajax code found in pos-types-admin.php.

And, @BGJamboree said above with Elementor: "When trying to post or update the process takes forever only to give a false completion. No changes are actually submitted when using Elementor. It would take a minimum of 5 minutes for the page to attempt to publish or update but when checking the front end, there were no changes actually published."

Then said the same thing happens in the Customizer.

I'm not sure from your questions if you're not seeing the same issues and if it could be related to other plugins they are both running or something, somewhere that's unique to them.

**Comment by pozitronios** [comment] 2020-07-24 16:51
@majick777 as commented above, If you want to recreate the problem try:
in toolset to create and/or edit a view
in elementor to save/update
in customizer to save/update

**Comment by majick777** [comment] 2020-07-25 04:56
@pozitronios Sorry I have not been able to test this further since we were given access to Toolset Types and Blocks but not Toolset Views... Hence my confusion trying to find the correct interface. So I have emailed asking for access to Toolset Views.

@BGJamboree You are probably correct that there is some AJAX action that is being processed unintentionally I will keep looking to see if I can find anything that is doing that.

**Comment by majick777** [comment] 2020-07-25 05:38
@BGJamboree Yes that was it, it was the new AJAX saving of shifts/tracks that was being triggered in other AJAX actions that use the `save_post` action.
@pozitronios Probably the same was causing the Toolset issue.

I have added the fix to dev version 2.3.2.2 for 2.3.3 release. If you can test it out this and report back as soon as you can, we would like to push this as a release fix as soon as we can as it significant enough to affect a variery of themes/plugins.
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing

**Comment by majick777** [comment] 2020-07-26 13:33
@pozitronios @BGJamboree Reports on WordPress.org support indicate this has resolved the issue so closing here. Feel free to comment if not the case and we can investigate further.

**Closed by majick777** 2020-07-26 13:33 UTC
Labels: bug

**Comment by tonyzeoli** [comment] 2020-07-27 04:13
v 2.3.3 is now available with a fix for this issue on the [WordPress plugin page.](https://wordpress.org/plugins/radio-station)

**Comment by BGJamboree** [comment] 2020-07-27 16:42
Thank you!!! Working like a charm 😊

**Comment by pozitronios** [comment] 2020-07-27 19:03
@majick777 Thanx! It Works!
