### ISSUE TITLE
[Show Shifts] Adding new show, shift won't save

### ISSUE THREAD

**Issue by boywondr16** [netmix/radio-station#192] opened 2020-04-20 19:46 UTC
I've run into this problem when adding a new show since updating to the current version: shift does not save. 

Everything else is saving, but no shift time is saving, as shown in the 3 screenshots attached.

I also have no access to change user roles...I downloaded the version of the plug-in from here today, disabled, deleted the previous version, uploaded the one I picked up today and still am having this problem.

![photo1](https://user-images.githubusercontent.com/4429395/79793093-442f8580-830d-11ea-9c6e-0545ffb2ea6f.jpg)

![photo2](https://user-images.githubusercontent.com/4429395/79793089-42fe5880-830d-11ea-8632-f17c05675786.jpg)

![photo3](https://user-images.githubusercontent.com/4429395/79793086-41cd2b80-830d-11ea-996a-b9a1ee86d5bd.jpg)

**Comment by majick777** [comment] 2020-04-26 12:04
This one is a bit tricky to debug without access to your admin to find out what is going on...
What you can try is adding `&rs-debug=1` to you edit page URL.
ie. `post.php?post=350716&action=edit&rs-debug=1`

Then when you click Update, after saving it should exit with some debug information output instead of redirecting back to the edit page.

**Comment by boywondr16** [comment] 2020-04-27 16:47
No luck. It took me right back to the edit page.

**Comment by boywondr16** [comment] 2020-04-27 17:04
Yeah, this just does not work. I've deleted out the directory from FTP and
reinstalled. Still nothing.

If you'd like, I can get you admin permissions. Just let me know, because
I'd like to be able to use the new version, but this is doing me no good
right now.

**Comment by majick777** [comment] 2020-04-29 09:22
This may be related to the user capabilities issue you posted on the WordPress Support Form and caused by that. The other user in that thread got around his problems by adding a new user and giving them the Show Editor role., so you can try that to conifirm whether it makes a difference. 
Did you check your user capabilities with the User Role Editor plugin yet? 

If this turns out not to be the cause, I'm happy to explore this issue further to get to the bottom of it., anything to do with core features like this is a priority fix.

**Comment by boywondr16** [comment] 2020-04-29 13:28
It is related, and thanks for your patience with me for double posting. I
did see the workaround and found that I could utilize it, too.

User Role Editor showed that the Administrator role had all permissions,
yet it took using the workaround to get a shift to post correctly.

Thanks, again! Appreciate you and Tony working so hard on this plugin.

**Comment by majick777** [comment] 2020-04-30 04:43
@boywondr16 Thanks for the further detail, this sure is a strange and tricky one. 

Can I just confirm whether you are on multisite or not as the other user was and I'm not sure if this is/was part of the issue.

One further thing you could try would be to remove the editing revocation from those without capabilities and not assigned as hosts/producers:
`<?php remove_filter( 'user_has_cap', 'radio_station_revoke_show_edit_cap', 10, 3 );`
(Place this in a .php file in /wp-content/mu-plugins/ or in your child theme functions,)

If that does bypass the issue then I will know that is the source of the problem and can re-visit the logic that is going on there.

**Comment by boywondr16** [comment] 2020-05-01 17:17
No, I'm not on multisite, just running on a single one.

Keeping track on the WP support site, too, so, again, thanks for the work!

**Comment by tonyzeoli** [comment] 2020-05-13 23:15
@boywondr16 can you let us know if this is still and issue, please?

**Comment by boywondr16** [comment] 2020-05-14 02:10
> @boywondr16 can you let us know if this is still and issue, please?

Just attempted after update and it still is an issue. I've been using the "second account" workaround, so it's not dramatically pressing, but it still is an issue.

**Comment by tonyzeoli** [comment] 2020-07-20 13:52
@boywondr16 Just doing some cleanup here. Let us know if you're issue is still persistent. So sorry for ignoring this since May  13, your last post, but I think this should be resolved. Let us know so we can close this Issue.

**Comment by boywondr16** [comment] 2020-07-20 14:49
You picked a good day to ask. I just had a reason to double-check and it
worked fine.

**Closed** 2020-09-17 01:36 UTC
Labels: bug, question
