### ISSUE TITLE
[Deprecated Warning] possible has_cap called with numeric argument

### ISSUE THREAD

**Issue by MattMski** [netmix/radio-station#423] opened 2022-05-27 18:33 UTC
**Describe the bug**
Hello, I am encountering a strange issue which I believe is coming from this plugin as I can't seem to figure it out. Turned on debug logs and I am getting the error, everytime I try to create a new show and save/publish:
Function has_cap was called with an argument that is deprecated since version 2.0.0! Usage of user levels is deprecated. Use capabilities instead.

**To Reproduce**
Set permissions for host to just be able to edit their own show and not publish. Every time I try to save/publish, I get: Sorry, you are not allowed to edit this post.

**Expected behavior**
It should let me save a draft, it worked before.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 102

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MattMski** [comment] 2022-05-27 19:15
Thank you, let me know if you need any more information from my end!

**Comment by majick777** [comment] 2022-05-28 04:13
@MattMski 

The warning is coming from checking a numeric capability somewhere:
https://developer.wordpress.org/reference/classes/wp_user/has_cap/

I searched the plugin and there are no calls to the `has_cap` function at all. What version of the plugin are you using? I don't recall any calls to it in the past but they might exist.

It's also possible there's another plugin installed that hooks into the `save_post` or `publish_post` hook that is being called when saving Shows. Unforunately we have no way of knowing which might be doing this in your case. You can try disabling individual plugins (process of elimination) or searching your installed plugins for the text string `has_cap`. Or install a debugger so you can get a backtrace on the error you are seeing.

**Comment by MattMski** [comment] 2022-05-28 15:49
@majick777 Thanks for the additional info.

I am using the latest version of the plugin so 2.4.0.9. I tried disabling all plugins besides the radio station one and it is still happening.

I did find has_cap in this plugin but once, as 
`add_filter( 'user_has_cap', 'radio_station_revoke_show_edit_cap', 10, 4 );`
on 2304 of radio-station.php

What debugger would you recommend to narrow this down?

**Comment by majick777** [comment] 2022-05-30 12:52
@MattMski That filter in Radio Station is called at the end of `has_cap`, however `current_user_can` is used in the plugin in a number of places, and this calls `has_cap` anyway ... I did some further searching but couldn't find many possibilities that would cause the error. With further testing I wasn't able to reproduce the error yet. It's possible it's a theme issue, perhaps you could test with a different theme?

Here's an error handler class that I've written to use for a debugger:
https://github.com/majick777/wp-triage/
If you install it as described there (to your wp-config.php), you can then do something like:
`http://example.com/wp-admin/?wpdebug=5&backtrace=notice`
and then navigate to the Show and save it as you are doing.
You should then be able to view your `/wp-content/debug.log` to see a backtrace.
(Another option you could try is the Query Monitor plugin, but I'm not sure it'll be able to do this for a POST request.)

**Comment by MattMski** [comment] 2022-11-15 19:36
Hey @majick777, it's been a while but got back to this. I can confirm it's still happening. 

I installed the plugin but it does not show any useful info other than the has_cap error.

**Comment by tonyzeoli** [comment] 2022-11-15 21:10
@MattMski The plugin is working correctly on our demo site, demo.radiostation.pro. It's also working correctly at https://uhhm.org. Did you switch to a base WordPress theme to check if it was your theme causing the error? Did you disable all plugins to assess a plugin conflict? Have you downloaded the latest development version at https://github.com/netmix/radio-station? Who is your hosting provider? Are you running php 7.x or 8?

**Comment by MattMski** [comment] 2022-11-15 21:35
I did switch themes, it is not theme related.
I disabled most plugins but will try again.
I am using the latest stable version
Hosting provider is hostgator and I am using PHP 7.x

Is it possible the roles got corrupt in the database? Would it be possible to reset them?

**Comment by tonyzeoli** [comment] 2022-11-15 22:01
@MattMski I would take the latest development version here on Git, but backup first and then upgrade and see if that resolves the issue. 

Fine to be on 7.4.

There isn't any kind of reset button for roles other than the main reset button in the Settings panel that exists on every panel page, but if you can't access that then you can't reset. 

Is there any way you can install a copy of Radio Station for WordPress on another host and see if that works with a temporary install? 

I can't imagine why it wouldn't work if it's working for me in multiple locations. Can you send me a temporary login to support@netmix.com and I'll accept and login and look around?

**Comment by tonyzeoli** [comment] 2022-11-15 22:02
Also, you might want to try to reinstall from the Plugin Dashboard and it should ask you which version you want to keep - you would keep the new version. Try that too.

**Comment by MattMski** [comment] 2022-11-15 22:09
> @MattMski I would take the latest development version here on Git, but backup first and then upgrade and see if that resolves the issue.
> 
> Fine to be on 7.4.
> 
> There isn't any kind of reset button for roles other than the main reset button in the Settings panel that exists on every panel page, but if you can't access that then you can't reset.
> 
> Is there any way you can install a copy of Radio Station for WordPress on another host and see if that works with a temporary install?
> 
> I can't imagine why it wouldn't work if it's working for me in multiple locations. Can you send me a temporary login to [support@netmix.com](mailto:support@netmix.com) and I'll accept and login and look around?

Sure absolutely, that would be helpful

**Comment by tonyzeoli** [comment] 2022-12-07 16:18
Closing this issue due to non response.

**Closed by tonyzeoli** 2022-12-07 16:18 UTC
Labels: question
