### ISSUE TITLE
[Show List] Edit Show Schedule Times differ from Show Times displayed in List View

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#99] opened 2019-12-27 03:28 UTC
**Is your developer task related to a problem or a requirement? Please describe.**
I found the Show Times in the Show Schedule on the Show page differ from the Show Times displayed in the Shows > List View.

**Describe the solution you'd like**
Please fix.

**Describe alternatives you've considered**
N/A

**Additional context**
See screenshots.

<img width="932" alt="Screen Shot 2019-12-26 at 10 26 15 PM" src="https://user-images.githubusercontent.com/4053819/71499560-08892100-282f-11ea-9e0b-461a993f8f32.png">
<img width="1235" alt="Screen Shot 2019-12-26 at 10 26 03 PM" src="https://user-images.githubusercontent.com/4053819/71499561-08892100-282f-11ea-9072-8817085495ef.png">

**Comment by majick777** [comment] 2019-12-28 00:02
Cannot seem to reproduce. Times match up for me and save correctly, maybe it was due to #100 or another fix I already made in the meantime. Can you retest?

PS. Can we make sure to file bugs in the Bugfixes Project not the Enhancements one, and if they are for the beta/development version tag it with the development label I just added, this way we can distinguish from bugs in the already released version.

**Comment by tonyzeoli** [comment] 2019-12-28 02:23
Okay, sorry, I was saving Bug Fixes for current bugs, but I'll move them. I'll retest now.

**Comment by tonyzeoli** [comment] 2019-12-28 02:33
For Show 3, when I try to set all shows from 2 am to 5 am, it will not save the values. The start time reverts back to 1 am.

There is one show conflict, which I'm going to try and resolve to see if that's the issue - maybe the conflict is causing the new times to not save.

**Comment by tonyzeoli** [comment] 2019-12-28 02:36
Okay, I just tried to change Show 1 times to 12 am to 1 am and all reverted to 1 am to 1 am.

**Comment by tonyzeoli** [comment] 2019-12-28 02:57
Here's a video: https://www.loom.com/share/403eaab027084930b6c0a32a2ff44555

**Comment by majick777** [comment] 2019-12-30 12:29
So there was a bug in start_hour selection matching, causing the new value to not be selected on the next page even though it was saved. Have tested your examples and seems to be working now. Retest and close if you're satisfied.

**Comment by majick777** [comment] 2020-01-12 00:52
@tonyzeoli Can you recheck and close if fixed.

**Comment by tonyzeoli** [comment] 2020-01-12 03:08
Looks like this is an issue with Show 12, which shows scheduled shows on the Calendar MON-FRI from 7 to 9, but not on the Show page. Says no shows scheduled.

**Comment by majick777** [comment] 2020-01-12 12:40
Puzzled me for a bit but then I realized Show 12 is not active... 
So I made this more obvious via highlighting in the List view.
Not sure if there is any further issue here or not.

**Comment by majick777** [comment] 2020-01-16 04:27
Going to close this one as it seems to be resolved, not seeing any further issues at this point.

**Closed by majick777** 2020-01-16 04:27 UTC
Labels: bug, development
