### ISSUE TITLE
Add Genres under Show Times in List View (like Tabbed View)

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#145] opened 2020-01-18 04:02 UTC
**Describe the bug**

Just noticed that we don't have Genres under Times like we do now in the Tabbed view.

**To Reproduce**
1. Go to List View
2. View List
3. No Genres under times

**Expected behavior**

Genres placed under Show Times like in Tabbed view.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment] 2020-01-19 02:08
Duplicate of #139

**Closed by majick777** 2020-01-19 02:08 UTC
Labels: bug
