### ISSUE TITLE
Only one DJ is listed in Show DJ module when multiple exist

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#19] opened 2019-07-25 01:01 UTC
**Describe the bug**
Only one DJ is listed in the DJ selection module in the Show Edit View when multiple DJs exist.

**To Reproduce**
1. Go to User table and check for all assigned DJs
2. If have multiple DJs, go to Dashboard > Show - Edit and click, Edit.
3. View all DJs in the Edit View DJs module.
4. Only One DJ displays (multiple times, has been reported as related issue.

**Expected behavior**

All users registered and assigned as DJ in Show > DJs module should display.

**Screenshots**

<img width="1548" alt="radio-station-dj-replicated-multiple-times" src="https://user-images.githubusercontent.com/4053819/61837878-c8271080-ae54-11e9-8444-722a27898b91.png">

**Comment by tonyzeoli** [comment] 2019-07-25 01:17
<img width="1548" alt="radio-station-user-table-with-DJs" src="https://user-images.githubusercontent.com/4053819/61838687-741e2b00-ae58-11e9-96ba-ef82a4cb25d3.png">

Here's a view of my user table with @nourmab13 and myself.

**Comment by majick777** [comment] 2019-07-25 03:30
Duplicate of #18 

This is an issue with the display labels, they have the different DJ IDs are selectable just displaying the same label for all of them. My bad on this one as I placed modified option label code (to include username) outside the user option loop. Fixed for next release.

**Closed by majick777** 2019-07-25 03:30 UTC
Labels: bug

**Comment by majick777** [comment] 2019-07-25 03:35
Duplicate of #18 

This is an issue with the display labels, they have the different DJ IDs are selectable just displaying the same label for all of them. My bad on this one as I placed modified option label code (to include username) outside the user option loop. Fixed for next release.

**Comment by majick777** [comment] 2019-07-25 03:39
Duplicate of #18 

This is an issue with the display labels, they have the different DJ IDs are selectable just displaying the same label for all of them. My bad on this one as I placed modified option label code (to include username) outside the user option loop. Fixed for next release.
