### ISSUE TITLE
[Show Status] Add Active checkbox to bulk edit and quick edit views

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#297] opened 2020-12-21 13:55 UTC
**Is your feature request related to a problem? Please describe.**
When a user wants to make multiple shows active or deactivate them at the same time.

**Describe the solution you'd like**
In the Bulk Edit and Quick Edit views, add the Active checkbox to allow the user to build edit the status of multiple shows quickly or make a show active or deactivate in the quick edit view.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by majick777** [comment] 2021-01-26 05:05
Duplicate of #294

**Closed by majick777** 2021-01-26 05:05 UTC
Labels: enhancement
