### ISSUE TITLE
Grid display time labels below cutoff lines

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#22] opened 2019-07-25 02:54 UTC
**Describe the bug**

If add Show and set two hour time for show, the calendar grid displays a a border between 1 am and 2 am. 

**To Reproduce**
1. View Calendar at https://netmix.co/radio-station-demo
2. View Show 1 and Show 2 entries for 12 midnight to 2 am.
3. Observe border for 2nd hour present when it should be the full two hour block without being split.

**Expected behavior**

The first hour and second-hour blocks should be combined and not be split into one block with data and a second block without.

**Screenshots**

<img width="1548" alt="Screen Shot 2019-07-24 at 10 49 20 PM" src="https://user-images.githubusercontent.com/4053819/61842346-cdd92200-ae65-11e9-8a10-4e89dfbf53a5.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment] 2019-07-25 04:20
I see this problem differently, there is no border already at 1am line, which is expected behaviour... the showtimeslot ends at 2am so does not continue into the third row. 

It may appear this way because the times display are below the line they are intended for (centered in the cell.) If we can shift up the time labels to where the lines actually are then the confusion will disappear.

**Comment by majick777** [comment] 2019-07-25 07:16
I have shifted the time labels up to be more in line with the lines, hopefully that will make things visually clearer. Added this one to next release.

**Comment by majick777** [comment] 2019-08-22 13:01
@tonyzeoli I saw on the demo site this issue may have arisen for longer program times, so I think it is worth reopening and exploring what may be actually happening there.

**Comment by tonyzeoli** [comment] 2019-08-29 13:10
Okay, sounds good.

**Comment by majick777** [comment] 2019-11-04 03:49
Related Bug Report: https://wordpress.org/support/topic/schedule-layout-broken-after-update/

As a result of this bug report, I have adjusted the CSS (for 2.3.0) to shift the hour label to the top of the cell by removing the cell padding top, instead of having a negative margin on the label div.  

Otherwise, table cells/shifts seem to be showing fine on all the test sites, so I'll close this issue.

**Closed by majick777** 2019-11-04 03:49 UTC
Labels: bug, question

**Comment by tonyzeoli** [comment] 2019-11-04 16:31
Gracias, senor!
